sentances:
  - I've got a $ that needs a a new name. Any suggestions?\nI was thinking about %
  - Should I call my new $, %?
  - Started a new $ project. What do people think of % for a name?
  - Is % a good name for a $?
  - I wish I could vote for president %
  - 'Lost: a poor little $ called %'

replies:
  - Maybe David Attenborough would be better!
  - Later to be named David Attenborough!
  - Or just David Attenborough!
  - Will David Attenborough now have to change his name?

nouns:
  - truck
  - boat
  - horse
  - art
  - map
  - computer
  - food
  - bird
  - thing
  - video
  - security
  - exam
  - movie
  - policy
  - camera
  - school
  - country
  - company
  - program
  - parse
  - job
  - home
  - room
  - book
  - business
  - game
  - car
  - bike
  - president
  - office
  - door
  - party
  - donk
  - cup
  - pen
  - stack
  - snack
  - whack
  - float
  - jug
  - anger
  - pant
  - leg
  - arm
  - sting
  - fling
  - prat
  - artichoke
  - ball
  - david
  - dog
  - cat 

